// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsNmBVTkvSkB4qX7qHxiPOO3CIweboIfM',
    appId: '1:611407556257:web:ca8d65026492b939618ae0',
    messagingSenderId: '611407556257',
    projectId: 'whatsapp-backend-4d88f',
    authDomain: 'whatsapp-backend-4d88f.firebaseapp.com',
    storageBucket: 'whatsapp-backend-4d88f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaJqbq0ooREkR8MHUlPhfDZONCG1G7xtI',
    appId: '1:611407556257:android:df8a0b0c52392762618ae0',
    messagingSenderId: '611407556257',
    projectId: 'whatsapp-backend-4d88f',
    storageBucket: 'whatsapp-backend-4d88f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk_5pRYInK2Cef-6YkCkUjk-VCGK0M90A',
    appId: '1:611407556257:ios:d6a96cf4d918870f618ae0',
    messagingSenderId: '611407556257',
    projectId: 'whatsapp-backend-4d88f',
    storageBucket: 'whatsapp-backend-4d88f.appspot.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
